import random
import simplegui
  
# This button changes range to [0,100) and restarts the game
def range100():
    global count
    global s0
    count = 7
    print ""
    print "New Game. Range is from 0 to 100"
    print "Number of remaining guesses is 7"
    s0 = random.randrange(0,100)
  
# This button changes range to [0,1000) and restarts the game    
def range1000():
    global count
    global s0
    count = 10
    print ""
    print "New Game. Range is from 0 to 1000"
    print "Number of remaining guesses is 10"  
    s0 = random.randrange(0,1000)
    
# Main game logic is written below            
def get_input(guess):
    global count
    global s0
    
   # Reducing number of guess available after each input & printing it
    count-=1                  
    print ""
    print "Guess was",guess
    print "Number of guesses remaining",count
    
   # Condition to check input number with respect to secret number generated by computer    
    if(s0 > int(guess)):
      print "Greater!"
    
    elif(s0 < int(guess)):
      print "Lower!"
    
    else:
      print "Correct!"
      print ""
      range100()
        
   # Condition to check whether you used up all your guesses        
    if(count == 0):
      print "You ran out of guesses.  The number was",s0
      print ""
      range100()
                        
# Frame created
frame = simplegui.create_frame("Guess the number", 200, 200)

# Event handlers registered for control elements
frame.add_button("Range is [0, 100)", range100, 200)
frame.add_button("Range is [0, 1000)", range1000, 200)
frame.add_input("Enter a guess", get_input, 200)

range100()

# Frame started
frame.start()
